{"operations":[{"i":-1,"o":1,"p":{"01621fb84e320000f001":"public","01692aa71f3108454479":true,"01703376c4a81c0e9d94":"stable","fdff023000000000000011":"Catch Errors","ff023000000000000011":"Catch Errors","v":2},"t":"016eeb5ede9f3094d8f5"},{"i":-1,"o":1,"p":{"01740c5d4ae4b520dd01":0,"ff023000000000000011":"Error Flow","v":1},"t":"016eeb5ede9f3094d8f6"},{"i":-1,"o":1,"p":{"01740c5d4ae4b520dd01":1,"ff023000000000000011":"Message","v":1},"t":"016eeb5ede9f3094d8f7"},{"i":-1,"o":1,"p":{"01740c5d4ae4b520dd01":2,"ff023000000000000011":"Code","v":1},"t":"016eeb5ede9f3094d8f8"},{"i":-1,"o":1,"p":{"01740c5d4ae4b520dd01":0,"ff023000000000000011":"Control Flow","v":1},"t":"016eeb5ede9f3094d8f9"},{"i":-1,"o":1,"p":{"01703376c4a81c0e9d91":"Catches errors and extract the details.","01703376c4a81c0e9d92":"Catching an error from an error-flow allows you to access its details and trigger a control-flow every time an error is thrown.","v":1},"t":"017b35893b9e8d9c06c3"},{"i":-1,"o":1,"p":{"01703376c4a81c0e9d92":"The error flow from which to catch errors.","v":1},"t":"017b35893faf9a7e567e"},{"i":-1,"o":1,"p":{"01703376c4a81c0e9d92":"The error message.","v":1},"t":"017b35894296e28286fa"},{"i":-1,"o":1,"p":{"01703376c4a81c0e9d92":"The output control flow.","v":1},"t":"017b35894297a075ba94"},{"i":-1,"o":1,"p":{"01703376c4a81c0e9d92":"The error code.","v":1},"t":"017b35894297e787717b"}],"optionalOperations":[],"rootTag":"016eeb5ede9f3094d8f5"}
